"""New Table

Revision ID: 18cb85102905
Revises: 483cda7f1dee
Create Date: 2022-11-16 17:15:53.173255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cb85102905'
down_revision = '483cda7f1dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IntShipLogModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tstamp', sa.Text(), nullable=True),
    sa.Column('customer', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('productName', sa.Text(), nullable=True),
    sa.Column('qrCode', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IntShipLogModel')
    # ### end Alembic commands ###
