"""new app

Revision ID: 483cda7f1dee
Revises: 
Create Date: 2022-11-11 12:42:47.081516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483cda7f1dee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory214',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('item_desc', sa.String(), nullable=True),
    sa.Column('item_ven', sa.String(), nullable=True),
    sa.Column('item_loc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('inventoryRFID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('item_desc', sa.String(), nullable=True),
    sa.Column('item_ven', sa.String(), nullable=True),
    sa.Column('item_loc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventoryRFID')
    op.drop_table('inventory214')
    # ### end Alembic commands ###
