"""delete table

Revision ID: c06634c072fd
Revises: 18cb85102905
Create Date: 2022-11-17 09:14:05.641278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06634c072fd'
down_revision = '18cb85102905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IntShipLogModel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IntShipLogModel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tstamp', sa.TEXT(), nullable=True),
    sa.Column('customer', sa.TEXT(), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('productName', sa.TEXT(), nullable=True),
    sa.Column('qrCode', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
